### ISSUE TITLE
set-cookie is being ignored

### ISSUE THREAD

**Issue by mikefrancis** [mikefrancis/laravel-secureheaders#1]
Ignoring cookies at the moment as Symfony seems deal with these headers slightly differently.

More info here: https://github.com/mikefrancis/laravel-secureheaders/commit/ddee8905e8237844554a124249c55e142396a803#commitcomment-23155954

**Comment by aidantwoods** [comment]
I took a bit of a more in-detail look at the Symfony code – it appears their cookie object does support the samesite attribute (I'd prefer arbitrary attributes, but I guess this works).

I still can't tell whether the support transfers to actually sending the attribute by looking at the code though. It would appear not, since they use PHPs `setcookie`/`setrawcookie` https://github.com/symfony/symfony/blob/22f6091bc7bc3a22d60b802693ccbfa37a5fb3a3/src/Symfony/Component/HttpFoundation/Response.php#L345, which do not support samesite. And even when they do, that won't be on 5.x.

Perhaps if you can confirm they don't, then open up a bug report to switch away from PHPs `setcookie` and just implement them in userland with `header` instead (they've already basically done this with the `__toString` method in their cookie object, so perhaps support is already in the works/I'm looking at unused code with the `setcookie` usage).

**Comment by aidantwoods** [comment]
Appears to be documented, so perhaps the attribute will work?

https://symfony.com/blog/new-in-symfony-3-2-httpfoundation-improvements

**Comment by mikefrancis** [comment]
Hmm, it doesn't seem to work as the `sameSite` value `Cookie` is being constructed with is `Lax` (uppercase L) and the constant [here](https://github.com/symfony/symfony/blob/22f6091bc7bc3a22d60b802693ccbfa37a5fb3a3/src/Symfony/Component/HttpFoundation/Cookie.php#L31) is a lowercase L, meaning the check [here](https://github.com/symfony/symfony/blob/22f6091bc7bc3a22d60b802693ccbfa37a5fb3a3/src/Symfony/Component/HttpFoundation/Cookie.php#L129) fails and an exception is thrown.

**Comment by mikefrancis** [comment]
Can't actually find where `SameSite=Lax` is being set 😕

**Comment by mikefrancis** [comment]
If I change [these](https://github.com/aidantwoods/SecureHeaders/blob/master/src/SecureHeaders.php#L2091) variables to be lowercase, it seems to work.

Is there a reason why these have uppercase first letters? (Or alternatively why Symfony would use lowercase?) Surely one of is these isn't adhering to a convention.

**Comment by aidantwoods** [comment]
Hmm that's interesting.

> (Or alternatively why Symfony would use lowercase?) Surely one of is these isn't adhering to a convention.

'Tis a good question. 

I haven't personally tested lower-case, however, per-spec it is wrong and should not work (though the spec is draft, and the wording is a little confusing in places). So Symfony's implementation may not actually work (at least in all browsers if they are following spec – some may be lenient on this).

See https://tools.ietf.org/html/draft-west-first-party-cookies-07#section-4.1

> 1.  If "cookie-av"'s "attribute-value" is not a case-sensitive match
>       for "Strict" or "Lax", ignore the "cookie-av".

Perhaps open a bug upstream in Symfony and reference this issue or the spec?

**Comment by aidantwoods** [comment]
I'd suggest that symfony match case insensitively, ~~but always use the capitalised first version (so as to correct any slightly wrong attributes if it finds them).~~

Looks like I checked an old spec draft 😆 more up to date one now says

> If "cookie-av"'s "attribute-value" is not a case-insensitive
> match for "Strict" or "Lax", ignore the "cookie-av".

So case-insensitive is the way to go (though matching all lower-case case sensitively is still wrong ;p)

**Comment by mikefrancis** [comment]
Thanks for the approval on that PR, fingers crossed it will get merged.

A little bit gutted this will only get pulled in for Laravel 5.4 onwards, as 5.3 is stuck on `symfony/http-foundation:3.1.*` and this fix is for `3.3` (Laravel 5.4 uses `~3.2` so will get picked up).

**Comment by aidantwoods** [comment]
Can you back-port the fix, or is `symfony/http-foundation:3.1.*` frozen now? (Since it's only a one line fix, might be worth back-porting to `3.2` too?)

I wonder if the team at symfony would go for a cookie/header implementation more similar to what's done in SecureHeaders (where attributes are preserved if they're not recognised). At present, if new cookie attributes/new values on SameSite are introduced then Symfony will need an update for each one (at each version that is still supported). Can kinda see the logic in throwing an exception if using a setter to flip the flag, but if it's coming from an already built header – seems like something that could (should?) be allowed through. 

Also see: https://tools.ietf.org/html/rfc6265#section-5.2 (algorithm for parsing the set-cookie-string), which doesn't care what the names are until the storage model for a user agent is described (Symfony is not a user agent, so should leave unknown attributes for the actual eventual user-agent (i.e browser) to interpret for itself IMO).
